baseURL = "https://raviwu.github.io"

title = "Ravi Wu"
languageCode = "zh-tw"
defaultContentLanguage = "zh"
theme = 'tale'

author = "Ravi Wu"
copyright = "Copyright © 2020, Ravi Wu."

publishDir = "docs"

[Author]
    name = "Ravi Wu"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    title = "tags"
    url = "/tags/"
    weight = 11
  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    title = "GitHub"
    url = "https://github.com/raviwu"
    weight = 91
  [[menu.main]]
    identifier = "linkedin"
    name = "Linkedin"
    title = "Linkedin"
    url = "https://www.linkedin.com/in/raviwu"
    weight = 90