baseURL = "https://raviwu.github.io/"

title = "Ravi Wu"
copyright = "Copyright © 2020 | Ravi Wu"
languageCode = "zh-TW"
defaultContentLanguage = "en-US"

publishDir = "docs"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

#disqusShortname = "myShortName"

# Note: to disable a social network icon delete or comment out the corresponding line
[author]
    name = "Ravi Wu"
    github = "https://github.com/raviwu"
    linkedin = "https://www.linkedin.com/in/raviwu/"
    #gitlab = "username"
    #facebook = "username"
    # twitter = "ds_says"
    #instagram = "username"
    #stackoverflow = "username"
    #youtube = "user/username" # or channel/channelname
    #devto = "username"

[params]
    tagline = "random thoughts and notes, beware if you want to reference"
    description = "Ravi Wu: random thoughts and notes, beware if you want to reference"
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = []  #Optional Customised CSS
    favicon = "favicon.ico"
    #utterancesRepo = "username/repository"
    #utterancesIssueTerm = "pathname"
    #homepageLength = 10
    #commentAutoload = true  #This mean reader don't need click, disqus comment autoload
    #mathjax = true #Enable display of mathematics using mathjax (LaTeX syntax)
    #katex = true #Enable display of mathematics using katex (Faster LaTeX rendering)
    #google_fonts = ["Staatliches"] # Adds additional google fonts
    #disableDarkModeCSS = false # disables css style for users using dark-mode

[[menu.main]]
   identifier = "about"
   name = "About"
   url = "/about"
   weight = 1

[[menu.main]]
   identifier = "tags"
   name = "Tags"
   url = "/tags"
   weight = 2
